# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3,4])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3,4],
              [5,6,7,8]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3,4],
               [11,22,33,44],
               [12,23,45,67]],
              [[98,76,54,32],
              [24,56,77,85],
              [65,76,3,7]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [5]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(f'Shape - {a1.shape} \nNo.of dimentions - {a1.ndim} \ndata type - {a1.dtype} \nsize - {a1.size} \ntype - {type(a1)}')

Shape - (4,) 
No.of dimentions - 1 
data type - int32 
size - 4 
type - <class 'numpy.ndarray'>


In [6]:
# Attributes of 2-dimensional array
print(f'Shape - {a2.shape} \nNo.of dimentions - {a2.ndim} \ndata type - {a2.dtype} \nsize - {a2.size} \ntype - {type(a2)}')

Shape - (2, 4) 
No.of dimentions - 2 
data type - int32 
size - 8 
type - <class 'numpy.ndarray'>


In [7]:
# Attributes of 3-dimensional array
print(f'Shape - {a3.shape} \nNo.of dimentions - {a3.ndim} \ndata type - {a3.dtype} \nsize - {a3.size} \ntype - {type(a3)}')

Shape - (2, 3, 4) 
No.of dimentions - 3 
data type - int32 
size - 24 
type - <class 'numpy.ndarray'>


In [9]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(data=a2, columns=['a','b','c','d'])
df

a  b  c  d
0  1  2  3  4
1  5  6  7  8

In [10]:
# Create an array of shape (10, 2) with only ones
np.ones(shape=(10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros(shape=(7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [13]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0,10,(7,2))

array([[2, 8],
       [0, 9],
       [8, 3],
       [2, 6],
       [3, 2],
       [5, 3],
       [2, 6]])

In [15]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.uniform(0,1,(3,5))

array([[0.68394646, 0.64378236, 0.86364505, 0.23896341, 0.32124039],
       [0.72190179, 0.91876804, 0.5930702 , 0.70504818, 0.87323171],
       [0.55247866, 0.069728  , 0.65862736, 0.50510444, 0.08716272]])

In [18]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0,10,(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [21]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rand_arr = np.random.randint(1,10,(3,7))

# Find the unique numbers in the array you just created
np.unique(rand_arr)

array([1, 2, 3, 5, 7, 8, 9])

In [27]:
rand_arr

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3],
       [1, 8, 3, 3, 1, 5, 7]])

In [24]:
# Find the 0'th index of the latest array you created
rand_arr[0][0]

2

In [26]:
# Get the first 2 rows of latest array you created
rand_arr[:2]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [29]:
# Get the first 2 values of the first 2 rows of the latest array
rand_arr[:2,:2]

array([[2, 5],
       [7, 9]])

In [30]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand = np.random.randint(0,10,(3,5))
ones = np.ones((3,5))
rand,ones

(array([[9, 8, 6, 8, 7],
        [1, 0, 6, 6, 7],
        [4, 2, 7, 5, 2]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [31]:
# Add the two arrays together
rand + ones

array([[10.,  9.,  7.,  9.,  8.],
       [ 2.,  1.,  7.,  7.,  8.],
       [ 5.,  3.,  8.,  6.,  3.]])

In [33]:
# Create another array of ones of shape (5, 3)
ones2 = np.ones((5,3))
ones2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
# Try add the array of ones and the other most recent array together
ones2 + rand

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [35]:
# Create another array of ones of shape (3, 5)
ones3 = np.ones((3,5))

In [37]:
# Subtract the new array of ones from the other most recent array
sub = rand - ones3
sub

array([[ 8.,  7.,  5.,  7.,  6.],
       [ 0., -1.,  5.,  5.,  6.],
       [ 3.,  1.,  6.,  4.,  1.]])

In [39]:
# Multiply the ones array with the latest array
mul = rand * sub
mul

array([[72., 56., 30., 56., 42.],
       [ 0., -0., 30., 30., 42.],
       [12.,  2., 42., 20.,  2.]])

In [42]:
# Take the latest array to the power of 2 using '**'
mul**2

array([[5.184e+03, 3.136e+03, 9.000e+02, 3.136e+03, 1.764e+03],
       [0.000e+00, 0.000e+00, 9.000e+02, 9.000e+02, 1.764e+03],
       [1.440e+02, 4.000e+00, 1.764e+03, 4.000e+02, 4.000e+00]])

In [43]:
# Do the same thing with np.square()
np.square(mul)

array([[5.184e+03, 3.136e+03, 9.000e+02, 3.136e+03, 1.764e+03],
       [0.000e+00, 0.000e+00, 9.000e+02, 9.000e+02, 1.764e+03],
       [1.440e+02, 4.000e+00, 1.764e+03, 4.000e+02, 4.000e+00]])

In [44]:
# Find the mean of the latest array using np.mean()
np.mean(mul)

29.066666666666666

In [45]:
# Find the maximum of the latest array using np.max()
np.max(mul)

72.0

In [48]:
# Find the minimum of the latest array using np.min()
np.min(rand)

0

In [49]:
# Find the standard deviation of the latest array
np.std(mul)

22.1011814666597

In [50]:
# Find the variance of the latest array
np.var(mul)

488.46222222222224

In [51]:
# Reshape the latest array to (3, 5, 1)
mul.reshape(3,5,1)

array([[[72.],
        [56.],
        [30.],
        [56.],
        [42.]],

       [[ 0.],
        [-0.],
        [30.],
        [30.],
        [42.]],

       [[12.],
        [ 2.],
        [42.],
        [20.],
        [ 2.]]])

In [54]:
# Transpose the latest array
mul.T

array([[72.,  0., 12.],
       [56., -0.,  2.],
       [30., 30., 42.],
       [56., 30., 20.],
       [42., 42.,  2.]])

What does the transpose do?

In [56]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,2))
arr1,arr2

(array([[3, 3, 4],
        [6, 6, 3],
        [6, 2, 5]]),
 array([[1, 9],
        [8, 4],
        [5, 3]]))

In [57]:
# Perform a dot product on the two newest arrays you created
np.dot(arr1,arr2)

array([[47, 51],
       [69, 87],
       [47, 77]])

In [58]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr1 = np.random.randint(0,10,(4,3))
arr2 = np.random.randint(0,10,(4,3))
arr1,arr2

(array([[9, 6, 8],
        [6, 0, 0],
        [8, 8, 3],
        [8, 2, 6]]),
 array([[5, 7, 8],
        [4, 0, 2],
        [9, 7, 5],
        [7, 8, 3]]))

In [59]:
# Perform a dot product on the two newest arrays you created
np.dot(arr1,arr2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [60]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(arr1,arr2.T)

array([[151,  52, 163, 135],
       [ 30,  24,  54,  42],
       [120,  38, 143, 129],
       [102,  44, 116,  90]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [61]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))

In [65]:
arr1,arr2

(array([[0, 0, 9],
        [3, 6, 1],
        [2, 0, 4]]),
 array([[0, 7, 0],
        [0, 1, 1],
        [5, 6, 4]]))

In [62]:
# Compare the two arrays with '>'
arr1 > arr2

array([[False, False,  True],
       [ True,  True, False],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [63]:
# Compare the two arrays with '>='
arr1 >= arr2

array([[ True, False,  True],
       [ True,  True,  True],
       [False, False,  True]])

In [64]:
# Find which elements of the first array are greater than 7
arr1 > 7

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [66]:
# Which parts of each array are equal? (try using '==')
arr1 == arr2

array([[ True, False, False],
       [False, False,  True],
       [False, False,  True]])

In [68]:
# Sort one of the arrays you just created in ascending order
arr1.sort()
arr1

array([[0, 0, 9],
       [1, 3, 6],
       [0, 2, 4]])

In [71]:
# Sort the indexes of one of the arrays you just created
arr2[2].sort()
arr2

array([[0, 7, 0],
       [0, 1, 1],
       [4, 5, 6]])

In [84]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr2)

1

In [85]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr2)

0

In [86]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr2, axis=1)

array([1, 1, 2], dtype=int64)

In [88]:
arr2

array([[0, 7, 0],
       [0, 1, 1],
       [4, 5, 6]])

In [87]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr2, axis=0)

array([0, 1, 0], dtype=int64)

In [94]:
# Create an array of normally distributed random numbers

# Parameters for the normal distribution
mean = 0       # Mean of the distribution
std_dev = 1    # Standard deviation
size = (3, 4)  # Shape of the array (3 rows, 4 columns)

# Create an array of normally distributed random numbers
random_array = np.random.normal(mean, std_dev, size)

print("Array of normally distributed random numbers:")
print(random_array)

Array of normally distributed random numbers:
[[-0.84661436  0.81615272  0.47170729 -0.2854893 ]
 [ 1.06529247  0.85399779  1.78859386  0.56689407]
 [-0.16450043 -0.14299093 -1.9345702   0.15065904]]


In [95]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.